name: pythonlatest
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12
  - pip
  - pip:
      - blinker==1.9.0
      - click==8.1.8
      - colorama==0.4.6
      - flask==3.1.0
      - flask-sock==0.7.0
      - h11==0.14.0
      - itsdangerous==2.2.0
      - jinja2==3.1.5
      - markupsafe==3.0.2
      - simple-websocket==1.1.0
